// <auto-generated />
namespace Site_Lab12.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecondMigr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondMigr));
        
        string IMigrationMetadata.Id
        {
            get { return "202001041832152_SecondMigr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
